/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.espaconatresende.view;

import br.com.espaconatresende.dao.ClientesDao;
import br.com.espaconatresende.dao.FornecedorDao;
import br.com.espaconatresende.dao.ProcedimentoDao; 
import br.com.espaconatresende.model.Clientes;
import br.com.espaconatresende.model.Fornecedores;
import br.com.espaconatresende.model.Procedimentos;
import br.com.espaconatresende.suport.SoNumeros;
import br.com.espaconatresende.suport.Utilitarios;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author power
 */
public class FrmProcedimento extends javax.swing.JFrame {

    public void positionFrame() {

        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw
                = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);

    }

    public void limparTela() {

        txtCodigoProcedimento.setText("");
        txtNomeProcedimento.setText("");
        comboTxtFornecedorProcedimento.setSelectedItem(0);
        jTextPrecoProcedimento.setText("");
        txtDescricao.setText("");

    }

    //metodo listar a tabela 
    public void listarTabela() {

        //criar um dao ja com conexao
        ProcedimentoDao dao = new ProcedimentoDao();

        //chama o metodo listar clientes da classe clientesdao e passa para a listaProcedimentos
        List<Procedimentos> lista = dao.listarProcedimentos();

        //define um dfalttable model fazendo o cast do modelo da tabela 
        DefaultTableModel dftm = (DefaultTableModel) tabelaProcedimentos.getModel();
        //seta valor inicial de apresentação de linha de dados para vazio
        dftm.setNumRows(0);

        for (Procedimentos p : lista) {
            dftm.addRow(new Object[]{
                p.getId(),
                p.getDescricaoProcedimento(),
                p.getNomeProcedimento(),
                p.getPreco()
              

            });

        }

    }

    /**
     * Creates new form FrmCliente
     */
    public FrmProcedimento() {
        initComponents();

        positionFrame();
        // txtNumero.setDocument(new SoNumeros());
        //txtCpf.setDocument(new SoNumeros());
        //txtCelular.setDocument(new SoNumeros());
        //txtTelefone.setDocument(new SoNumeros());

        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTableAbasProcedimentos = new javax.swing.JTabbedPane();
        painelCadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoProcedimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProcedimento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPesquisarProcedimento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextPrecoProcedimento = new javax.swing.JFormattedTextField();
        comboTxtFornecedorProcedimento = new javax.swing.JComboBox();
        PainelProcedimentos = new javax.swing.JPanel();
        jTextPesquisar = new javax.swing.JTextField();
        btnConsultarProcedimento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProcedimentos = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btnCancelarConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Espaço Natalia Rezende");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastro de Procedimentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelTitulo)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTableAbasProcedimentos.setBackground(new java.awt.Color(255, 255, 255));
        jTableAbasProcedimentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAbasProcedimentos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTableAbasProcedimentosStateChanged(evt);
            }
        });

        painelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código :");

        txtCodigoProcedimento.setEditable(false);
        txtCodigoProcedimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigoProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProcedimentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome Procediemento:");

        txtNomeProcedimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProcedimentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Preço Procedimento :");

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditar.setText("SALVAR EDIÇÃO");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPesquisarProcedimento.setText("PESQUISAR PROCEDIMENTO");
        btnPesquisarProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProcedimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Descrição :");

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Fornecedor Procedimento :");

        jTextPrecoProcedimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        comboTxtFornecedorProcedimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboTxtFornecedorProcedimento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboTxtFornecedorProcedimentoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(btnCancelar))
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPrecoProcedimento, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(comboTxtFornecedorProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnExcluir))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addGap(47, 47, 47)
                                .addComponent(btnSalvar)
                                .addGap(30, 30, 30)
                                .addComponent(btnEditar))))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(txtNomeProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisarProcedimento)))))
                .addGap(129, 129, 129))
        );

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnEditar, btnExcluir, btnNovo, btnPesquisarProcedimento, btnSalvar});

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboTxtFornecedorProcedimento, jTextPrecoProcedimento});

        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProcedimento)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboTxtFornecedorProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextPrecoProcedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnEditar, btnExcluir, btnNovo, btnPesquisarProcedimento, btnSalvar});

        painelCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboTxtFornecedorProcedimento, jTextPrecoProcedimento});

        jTableAbasProcedimentos.addTab("Cadastro de Procedimentos ", painelCadastro);
        painelCadastro.getAccessibleContext().setAccessibleName("");
        painelCadastro.getAccessibleContext().setAccessibleDescription("");

        PainelProcedimentos.setBackground(new java.awt.Color(255, 255, 255));
        PainelProcedimentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PainelProcedimentosFocusGained(evt);
            }
        });
        PainelProcedimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelProcedimentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PainelProcedimentosMouseEntered(evt);
            }
        });
        PainelProcedimentos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PainelProcedimentosPropertyChange(evt);
            }
        });

        jTextPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPesquisarActionPerformed(evt);
            }
        });

        btnConsultarProcedimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConsultarProcedimento.setText("Consultar Procedimento");
        btnConsultarProcedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProcedimentoActionPerformed(evt);
            }
        });

        tabelaProcedimentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaProcedimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fornecedor", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaProcedimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProcedimentosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaProcedimentosMouseReleased(evt);
            }
        });
        tabelaProcedimentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaProcedimentosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProcedimentos);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Nome Procedimento:");

        btnCancelarConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelarConsulta.setText("Cancelar");
        btnCancelarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelProcedimentosLayout = new javax.swing.GroupLayout(PainelProcedimentos);
        PainelProcedimentos.setLayout(PainelProcedimentosLayout);
        PainelProcedimentosLayout.setHorizontalGroup(
            PainelProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProcedimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelProcedimentosLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarProcedimento)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelProcedimentosLayout.setVerticalGroup(
            PainelProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProcedimentosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PainelProcedimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarProcedimento)
                    .addComponent(btnCancelarConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTableAbasProcedimentos.addTab("Pesquisa Procedimentos", PainelProcedimentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTableAbasProcedimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTableAbasProcedimentos)
                .addGap(7, 7, 7))
        );

        setBounds(0, 0, 1199, 743);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPesquisarActionPerformed


    private void btnConsultarProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProcedimentoActionPerformed
        String nomeProcedimento = jTextPesquisar.getText();

        ProcedimentoDao dao = new ProcedimentoDao();

        //chama o metodo listar clientes da classe clientesdao e passa para a listaProcedimentos
        List<Procedimentos> listaProcedimentos = dao.consultarProdedimentoPeloNomeCompleto(nomeProcedimento);

        //define um dfalttable model fazendo o cast do modelo da tabela 
        DefaultTableModel dftm = (DefaultTableModel) tabelaProcedimentos.getModel();
        //seta valor inicial de apresentação de linha de dados para vazio
        dftm.setNumRows(0);

        for (Procedimentos p : listaProcedimentos) {
            dftm.addRow(new Object[]{
              

            });

        }        // TODO add your handling code here:

        //pesquisa de cliente
        try {

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnConsultarProcedimentoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        this.setVisible(true);

        listarTabela();

        //carregar a listaProcedimentos no painel
    }//GEN-LAST:event_formWindowActivated

    private void tabelaProcedimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProcedimentosMouseClicked
        /*        // TODO add your handling code here:
        //passando dados do listaProcedimentos para os campos da primeira tela
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(true);

        //caixa de confirmação
        Object[] options = {"Cancelar", "Confirmar"};
        int op = JOptionPane.showOptionDialog(null, "Deseja abrir o contato para edição?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (op == 1) {
            btnEditar.setEnabled(true);
            jTableAbas.setSelectedIndex(0);

            txtCodigo.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0).toString());
            txtNome.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1).toString());
            txtRg.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 2).toString());
            txtCpf.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 3).toString());
            txtEmail.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 4).toString());
            txtCelular.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 5).toString());
            txtTelefone.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 6).toString());
            txtCep.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 7).toString());
            txtEndereco.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 8).toString());
            txtNumero.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 9).toString());
            txtComplemento.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 10).toString());
            txtBairro.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 11).toString());
            txtCidade.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 12).toString());
            comboTxtEstado.setSelectedItem(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 13).toString());
            txtNascimento.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 14).toString());

        }*/


    }//GEN-LAST:event_tabelaProcedimentosMouseClicked

    private void tabelaProcedimentosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProcedimentosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaProcedimentosMouseReleased

    private void tabelaProcedimentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProcedimentosKeyPressed

        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                btnNovo.setEnabled(false);
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(true);
                btnPesquisarProcedimento.setEnabled(false);

                //caixa de confirmação
                Object[] options = {"Cancelar", "Confirmar"};
                int op = JOptionPane.showOptionDialog(null, "Deseja abrir o contato para edição?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

                if (op == 1) {
                    btnEditar.setEnabled(true);
                    jTableAbasProcedimentos.setSelectedIndex(0);

                    txtCodigoProcedimento.setText(tabelaProcedimentos.getValueAt(tabelaProcedimentos.getSelectedRow(), 0).toString());
                    txtNomeProcedimento.setText(tabelaProcedimentos.getValueAt(tabelaProcedimentos.getSelectedRow(), 1).toString());
                    Fornecedores f = new Fornecedores();
                    FornecedorDao dao = new FornecedorDao();
                    f = dao.pesquisaFornecedorPelaMarca(tabelaProcedimentos.getValueAt(tabelaProcedimentos.getSelectedRow(), 2).toString());

                    comboTxtFornecedorProcedimento.removeAllItems();

                    comboTxtFornecedorProcedimento.getModel().setSelectedItem(f);
                    jTextPrecoProcedimento.setText(tabelaProcedimentos.getValueAt(tabelaProcedimentos.getSelectedRow(), 3).toString());
                   
                    txtDescricao.setText(tabelaProcedimentos.getValueAt(tabelaProcedimentos.getSelectedRow(), 5).toString());

                }

            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_tabelaProcedimentosKeyPressed

    private void btnPesquisarProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProcedimentoActionPerformed
        // TODO add your handling code here:

        //botao buscar por nome
        try {
            //pega string do campo na tela

            String nome = txtNomeProcedimento.getText();

          

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnPesquisarProcedimentoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparTela();

        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        // TODO add your handling code here:
        //excluir cliente
        try {


        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao excluir Produto! " + e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        //editar contato
        try {

          
        } catch (Exception e) {

            if (e.toString().contains("empty String")) {
                JOptionPane.showMessageDialog(null, "Valor do Produto precisa ser preenchido");
            }

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        // TODO add your handling code here:
        //botao salvar
        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);

        if (txtNomeProcedimento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome do produto precisa ser preechido.");

        } else {
            try {

             

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Erro ao salvar cliente! " + e);
                System.out.println(jTextPrecoProcedimento.getText().toString());
            }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:

        limparTela();

        btnNovo.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnPesquisarProcedimento.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void txtNomeProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProcedimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProcedimentoActionPerformed

    private void txtCodigoProcedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProcedimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProcedimentoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void comboTxtFornecedorProcedimentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboTxtFornecedorProcedimentoAncestorAdded
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedores> listaDeFornecedores = dao.listarFornecedores();
        comboTxtFornecedorProcedimento.removeAll();

        for (Fornecedores f : listaDeFornecedores) {

            comboTxtFornecedorProcedimento.addItem(f);

        }
    }//GEN-LAST:event_comboTxtFornecedorProcedimentoAncestorAdded

    private void btnCancelarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarConsultaActionPerformed
        // TODO add your handling code here:

        listarTabela();
    }//GEN-LAST:event_btnCancelarConsultaActionPerformed

    private void PainelProcedimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelProcedimentosMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PainelProcedimentosMouseClicked

    private void PainelProcedimentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelProcedimentosMouseEntered
        // TODO add your handling code here:
     
    }//GEN-LAST:event_PainelProcedimentosMouseEntered

    private void jTableAbasProcedimentosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTableAbasProcedimentosStateChanged
        // TODO add your handling code here:
       
          
    }//GEN-LAST:event_jTableAbasProcedimentosStateChanged

    private void PainelProcedimentosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PainelProcedimentosFocusGained
         // TODO add your handling code here:
    }//GEN-LAST:event_PainelProcedimentosFocusGained

    private void PainelProcedimentosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PainelProcedimentosPropertyChange
        // TODO add your handling code here:
      
    }//GEN-LAST:event_PainelProcedimentosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProcedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProcedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProcedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProcedimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProcedimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelProcedimentos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarConsulta;
    private javax.swing.JButton btnConsultarProcedimento;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarProcedimento;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox comboTxtFornecedorProcedimento;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTableAbasProcedimentos;
    private javax.swing.JTextField jTextPesquisar;
    private javax.swing.JFormattedTextField jTextPrecoProcedimento;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JTable tabelaProcedimentos;
    private javax.swing.JTextField txtCodigoProcedimento;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomeProcedimento;
    // End of variables declaration//GEN-END:variables
}
